language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - python-dev
      - python-numpy

before_script:
  - #git clone -b java_overloads https://github.com/dkurt/opencv
  - #git clone -b java_MatOfRotatedRect_utils https://github.com/berak/opencv
  - git clone -b 3.4 https://github.com/opencv/opencv
  - #git pull https://github.com/berak/opencv_contrib test_face_test
  - #git pull https://github.com/alalek/opencv_contrib merge-3.4
script:
  - #python --version
  - pwd
  - mkdir ocv
  - cd opencv
  - mkdir build
  - cd build
  - echo -n cmake -DBUILD_LIST=\"core,dnn,imgproc,imgcodecs\" -WITH_ITT= >> cm.sh
  - #echo -n cmake -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -DBUILD_LIST=\"objdetect,face,plot,dnn,core,calib3d,imgproc,imgcodecs,flann,python2,python,python_bindings_generator\" -WITH_ITT= >> cm.sh
  - #echo -n cmake -DBUILD_opencv_face=ON -DBUILD_opencv_test_java=ON -DBUILD_opencv_ml=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_video=ON -DBUILD_opencv_videoio=OFF -DBUILD_opencv_highgui=OFF -DBUILD_opencv_objdetect=ON -WITH_ITT= >> cm.sh
  - echo -n OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -WITH_IPP=OFF -DBUILD_IPP_IW=OFF -DBUILD_WITH_DYNAMIC_IPP=OFF -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS= >> cm.sh
  - echo -n OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_examples=OFF -DWITH_OPENEXR=OFF -DBUILD_OPENEXR= >> cm.sh
  - echo -n OFF -DCV_TRACE=OFF -DWITH_TIFF=OFF -DWITH_EXR=OFF  >> cm.sh
  - echo -n -DBUILD_ZLIB=ON -DWITH_WEBP=OFF -DWITH_JASPER=>> cm.sh
  - echo -n OFF >> cm.sh
  - echo -G \"Unix Makefiles\" .. >> cm.sh
  - cat cm.sh
  - bash cm.sh
  - make -j8 install
  - #ls modules/java_bindings_generator/gen
  - #cat modules/python_bindings_generator/pyopencv_generated_funcs.h
  - #cat modules/java/jar/opencv/java/org/opencv/calib3d/Calib3d.java
  - #cat modules/java/gen/face+MACE.java
  - #echo run java tests
  - #python ../modules/ts/misc/run.py . -t java
  - cd ..
  - cd ..
  - wget https://drive.google.com/open?id=15EsVuuDd2gHN9uBN70NDaglX4as2UwyC -O crnn.onnx
  - ls -l
  - make
  - #g++ -I/usr/local/include -L/usr/local/lib crnn.cpp -lopencv_core -lopencv_dnn -lopencv_imgproc -lopencv_imgcodecs -o crnn
  - ./crnn

notifications:
  email: false
